### ISSUE TITLE
import error with docker 

### ISSUE THREAD

**Issue by wendwosenbb** [Yarroudh/segment-lidar#19]
hi,  thanks for publishing this cool packages.
But, I am having issue with CSF module not being found in the docker image of segment-lidar.
`fw@w-Crosshair-15-A11UCK:~/lidar_segmentation$ docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED             STATUS             PORTS     NAMES
01cf113224e7   yarroudh/segment-lidar   "python -c 'while Tr…"   About an hour ago   Up About an hour             priceless_wu
w@w-Crosshair-15-A11UCK:~/lidar_segmentation$ docker exec 01cf113224e7 python segment.py
Traceback (most recent call last):
  File "segment.py", line 1, in <module>
    from segment_lidar import samlidar, view
  File "/opt/conda/lib/python3.8/site-packages/segment_lidar/samlidar.py", line 6, in <module>
    import CSF
ModuleNotFoundError: No module named 'CSF'
`
I also  installed CSF inside the docker, but still CSF is not found.

**Comment by Yarroudh** [comment]
Hello @wendwosenbb,
Thanks for reporting this error. The docker image should be updated. I encourage you to install the package on a local environment. Once updated, I will inform you here.

**Comment by joelkny97** [comment]
Was this issue fixed ?
