### ISSUE TITLE
error during inference 

### ISSUE THREAD

**Issue by pedrozamboni** [Yarroudh/segment-lidar#27]
Hi, 

Did somebody get this error ??? 

Traceback (most recent call last):
  File "/home/pedro/Documents/Documents/projects/pointcloud/h3d/zim_v1/samlidar.py", line 10, in <module>
    labels, *_ = model.segment(points=points, view=viewpoint)
  File "/home/pedro/anaconda3/envs/samlidar/lib/python3.9/site-packages/segment_lidar/samlidar.py", line 285, in segment
    os.makedirs(directory)
  File "/home/pedro/anaconda3/envs/samlidar/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)

**Comment by surajsharma2111** [comment]
did you find the solution for your problem?

**Comment by Amr-Hegazy1** [comment]
I ran into the same issue and found that #22 solved it
